name: Merge PR to main

permissions:
  contents: read

on:
  pull_request:
    types:
      - closed
      # - opened
      # - reopened
      # - synchronize
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write

    if: github.event.pull_request.merged == true # Ensure the PR was merged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies for Semantic Versioning
        run: |
          python -m pip install --upgrade pip
          pip install tomli tomli-w

      - name: Get Base and Latest Commits of the Merged PR
        id: commit-range
        run: |
          # Get the base commit of the PR (the commit where it diverged from the main branch)
          BASE_COMMIT=$(git merge-base HEAD^ origin/main)

          # Get the commits introduced by this PR
          COMMITS=$(git rev-list --reverse $BASE_COMMIT..HEAD)

          # Extract the first and last commits
          FIRST_COMMIT=$(echo "$COMMITS" | head -n 1)
          LATEST_COMMIT=$(echo "$COMMITS" | tail -n 1)

          # Set outputs for later steps
          echo "base_commit=$BASE_COMMIT" >> $GITHUB_OUTPUT
          echo "first_commit=$FIRST_COMMIT" >> $GITHUB_OUTPUT
          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT

          # Log for debugging
          echo "Base Commit: $BASE_COMMIT"
          echo "First Commit in PR: $FIRST_COMMIT"
          echo "Latest Commit in PR: $LATEST_COMMIT"

      - name: Get Latest Feluda Tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git tag -l "feluda-[0-9]*" | sort -V | tail -n1)
          echo "current_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "current feluda tag: $LATEST_TAG"

      - name: Run Dynamic Semantic Release Script
        env:
          FIRST_COMMIT: ${{ steps.commit-range.outputs.first_commit }}
          LATEST_COMMIT: ${{ steps.commit-range.outputs.latest_commit }}
        run: |
          pwd
          # run the script
          python -m scripts.semantic_release_workflow "$FIRST_COMMIT" "$LATEST_COMMIT"

      - name: Commit and Push Changes
        id: push-changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"

          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "chore: bump version and update related files"
            git push
            git push --tags

            # Check if new feluda tag was created
            NEW_TAG=$(git tag -l "feluda-[0-9]*" | sort -V | tail -n1)
            if [ "$NEW_TAG" != "${{ steps.latest-tag.outputs.current_tag }}" ]; then
              echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
              echo "tag_created=true" >> $GITHUB_OUTPUT
            else
              echo "tag_created=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "tag_created=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.push-changes.outputs.tag_created == 'true'
        run: |
          gh release create "${{ steps.push-changes.outputs.new_tag }}" \
            --repo="${GITHUB_REPOSITORY}" \
            --title="Release ${{ steps.push-changes.outputs.new_tag }}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
