name: Test Semantic Release Workflow

on:
  pull_request:
    branches:
      - main
      - development
      - hotfix
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  test-semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest tomlkit

      - name: Run Semantic Release Tests
        run: pytest tests/
